#path: docker-compose.yml
services:
#for api services:
  identity-service:
    build:
      context: ./apis/identity-service
      dockerfile: Dockerfile
    depends_on:
      - "sqlserver-db"
      - "message-broker"
  product-service:
    build:
      context: ./apis/product-service
      dockerfile: Dockerfile
    depends_on:
      - "mysql-db"
      - "message-broker" 
  #for client web app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1404:3000"
  #for admin web app

  #for sql server database
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "3307:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer # MSSQL_PID can be: Developer, Express, Standard, Enterprise, or Evaluation
    volumes:
      - sqlserver-data:/var/opt/mssql
  #for mysql database
  mysql-db:
    image: mysql:latest
    command: 
      - --default-authentication-plugin=mysql_native_password # để sử dụng password bình thường thay vì password mạnh
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
  #adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  #for nginx api gateway
  api-gateway:
    image: nginx:latest
    restart: always
    #sử dụng file cấu hình ở thư mục ./etc/nginx/nginx.conf
    depends_on:
      - "identity-service"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  # for rabbitmq
  message-broker:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
volumes:
  mysql-data:
  sqlserver-data: