#path: docker-compose.yml
services:
  identity-service:
    build:
      context: ./apis/identity-service
      dockerfile: Dockerfile
    depends_on:
      - "mysql-db"
  product-service:
    build:
      context: ./apis/product-service
      dockerfile: Dockerfile
    depends_on:
      - "mysql-db"
  #for mysql database
  mysql-db:
    image: mysql:8.1.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
  #for nginx api gateway
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    #sử dụng file cấu hình ở thư mục ./etc/nginx/nginx.conf
    depends_on:
      - "identity-service"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  #adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "mysql-db"
volumes:
  mysql: