import './globals.css'
import type {Metadata} from 'next'
import Header from "@/app/components/header/Header";

export const metadata: Metadata = {
    title: 'clgt',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (

        <html lang="en" suppressHydrationWarning={true}>
        <head>
            <title>{metadata.title as unknown as string}</title>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </head>
        <body>
        <Header/>
        <div>
            {children}
        </div>
        </body>
        </html>
    )
}
